language: node_js
node_js: 
  - 13

services: 
  - docker

#pre-testing installs
install:
  - echo "nothing needs to be installed"

# script to be run such as tests
before_script:
  - echo "no test"

script: 
  - docker --version


after_success: 
  - echo "nothing for now"